import type { Campaign, WorkflowStep } from './types';

export const createInfluencerWorkflow = (): WorkflowStep[] => [
    { id: 1, title: "Application Accepted!", status: 'Completed', date: new Date(Date.now() - 86400000).toLocaleString(), description: "The brand has accepted your application. Welcome aboard!"},
    { id: 2, title: "Receive Product", status: 'Waiting', date: 'Waiting for Tracking Info', description: "The brand will ship the product to you shortly. We will update this step with tracking information once available."},
    { id: 3, title: "Submit Script for Review", status: 'Action Needed', date: new Date().toLocaleString(), description: "Please create a script or content outline based on the campaign brief and submit it for brand approval.", actionLabel: "Submit Script"},
    { id: 4, title: "Create Content", status: 'Upcoming', description: "Once your script is approved, it's time to create the amazing content!"},
    { id: 5, title: "Post Content & Provide Link", status: 'Upcoming', description: "After the brand approves your final content, post it to your social media and submit the live link here."},
    { id: 6, title: "Payment Processing", status: 'Upcoming', description: "Once the campaign is complete, your payment will be processed."},
];


export const mockCampaigns: Campaign[] = [
    {
        id: 1,
        brandName: "Wow! Momo",
        campaignTitle: "Product Promotion Barter campaign",
        campaignImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ7g_QSmCo4_eY_k5p1J_2-qlBibmGNlqX1-g&s",
        tags: ["Food & Grocery", "Lifestyle"],
        compensation: "Barter (Value up to ₹3000)",
        specifications: {
            brand: "Wow Momo",
            budget: "upto ₹2930 (includes ₹3000 barter value)",
            influencerAge: "18 - 35",
            influencerLocation: "Bangalore, Karnataka",
            followers: "20000+",
            audienceLocation: "Bangalore, Karnataka",
            audienceAge: "18-24, 25-34, 35-44",
        },
        description: "We're on the lookout for creators who love adding a touch of authenticity to everyday moments! Whether it's sipping on the pure goodness of Coco Charge or slurping the global flavors of Wow! Instant Noodles, we want to see your version of comfort and convenience.\n\nTogether, let's craft stories that feel genuine, engaging, and full of flavor!",
        contentReferences: [
            { title: "Creative 1: Cocktail Reel", url: "https://www.instagram.com/reel/DMSG7eeSKiX/?hl=en" },
            { title: "Creative 2: Trendy Reel", url: "https://www.instagram.com/reel/C2AbCdEfGhj/?hl=en" },
        ],
        deliverables: ["1 Collab Reel with either of our pages: @wowmomoinstant @thecococharge"],
        cta: ["Use a creative call-to-action that subtly highlights how viewers can grab these products at the best ongoing offers by clicking the link in the caption."],
        mediaRequirements: { reels: 1, stories: 1, posts: 0 },
        paymentTerms: "7 days",
        aboutTheBrand: "Innovation-first is not just noodles, it's flavor, convenience, and global inspiration — reimagined in a cup.",
    },
    {
        id: 2,
        brandName: "Jamnagar Giga Energy Complex",
        campaignTitle: "Promotional Campaign",
        campaignImage: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhx4lB-pC87rVz-Hl3j4K7e8wX9qZ9p8-n0e4Y7m5n0g8wZ1o3i9K0h7wZ5m9-t2k6j6e6r5t7l3w7x3d8c2s1w0f1c3a2b1/s1600/reliance_jamnagar_giga_complex.webp",
        tags: ["Technology", "Energy", "Sustainability"],
        compensation: "Paid (Performance-based)",
        specifications: {
            brand: "Reliance Industries",
            budget: "Performance-based",
            influencerAge: "25+",
            influencerLocation: "India",
            followers: "100000+",
            audienceLocation: "Global",
            audienceAge: "25-55",
        },
        description: "Highlighting the future of green energy with the Jamnagar Giga Energy Complex. We are looking for tech and sustainability influencers to create content about this groundbreaking initiative.",
        contentReferences: [],
        deliverables: ["1 Detailed YouTube Video", "3 Instagram Stories"],
        cta: ["Drive awareness about green energy initiatives and direct followers to our corporate sustainability page."],
        mediaRequirements: { reels: 0, stories: 3, posts: 0 },
        paymentTerms: "30 days post-campaign",
        aboutTheBrand: "Reliance Industries is building one of the world’s largest integrated renewable energy manufacturing facilities in Jamnagar, India.",
    },
     {
        id: 3,
        brandName: "UrbanStyle",
        campaignTitle: "Summer Fashion Showcase",
        campaignImage: "https://images.unsplash.com/photo-1483985988355-763728e1935b?q=80&w=2070&auto=format&fit=crop",
        tags: ["Fashion", "Lifestyle", "Apparel"],
        compensation: "Paid (₹15,000)",
        specifications: {
            brand: "UrbanStyle Co.",
            budget: "₹15,000 per influencer",
            influencerAge: "18-30",
            influencerLocation: "Any",
            followers: "10000+",
            audienceLocation: "Tier 1 & 2 Cities",
            audienceAge: "18-30",
        },
        description: "Show off your summer style with our new collection! We're looking for fashion-forward creators to produce a stunning lookbook-style Reel showcasing our latest summer apparel.",
        contentReferences: [],
        deliverables: ["1 Instagram Reel (min. 30 seconds)", "3 Instagram Stories with swipe-up links"],
        cta: ["Direct followers to our new collection page with a special discount code provided to you."],
        mediaRequirements: { reels: 1, stories: 3, posts: 0 },
        paymentTerms: "15 days after campaign completion",
        aboutTheBrand: "UrbanStyle brings the latest runway trends to your wardrobe at affordable prices.",
    },
];
